# Generated by Django 5.1.3 on 2024-11-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity_multimedia_article_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
